sudo: false

os:
  - osx
  - linux

addons:
  apt_packages:
    - pandoc

env:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.3
  - PYTHON_VERSION=3.4
  - PYTHON_VERSION=3.5

before_install:
  - export CONDA_CACHED=1
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export OS=Linux;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export OS=MacOSX;
      brew install pandoc; 
    else
      echo "OS not supported yet";
      exit 1;
    fi;
  - if [[ $PYTHON_VERSION == "2.7" ]]; then
      export MINICONDA=Miniconda;
    elif [[ $PYTHON_VERSION == 3* ]]; then
      export MINICONDA=Miniconda3;
    else
      echo "Could not find python version";
      exit 1;
    fi;
  - if [ ! -d $HOME/download/ ]; then mkdir $HOME/download/; fi;
  - if [ ! -d $HOME/install/ ]; then mkdir $HOME/install/; fi;
  - export MINICONDA_FILE=$MINICONDA-latest-$OS-x86_64-$PYTHON_VERSION
  - export MINCONDA_CACHE_FILE=$HOME/download/$MINICONDA_FILE.sh
  - export MINICONDA_INSTALL=$HOME/install/$MINICONDA_FILE
  - if [ ! -f $MINCONDA_CACHE_FILE ]; then
      export CONDA_CACHED=0;
      wget http://repo.continuum.io/miniconda/$MINICONDA-latest-$OS-x86_64.sh -O $MINCONDA_CACHE_FILE;
      bash $MINCONDA_CACHE_FILE -b -p $MINICONDA_INSTALL;
    fi;
  - export PATH="$MINICONDA_INSTALL/bin:$PATH";
  
install:
  - conda install --yes python=$PYTHON_VERSION numpy=1.9 scipy=0.16 nose pip six matplotlib;
  - pip install codecov
  - pip install pypandoc
  - python setup.py develop
   
script:
  - coverage run travis_tests.py

after_success:
  - codecov
  
before_deploy:
  - cd doc
  - pip install sphinx_rtd_theme
  - sphinx-apidoc -o source/ ../paramz
  - make html
  - cd ../

deploy:
  provider: pypi
  user: maxz
  password: 
    secure: "YS6Ue660FfMWs9wnCtWK3er2i3AgYsfYXEMIVHIIFT7U/l6MPJAlneUYbOz9bniQ/oYmG1/4NBJdDGryOnMmovXIuHmvG3XKrPVHT+m7C63+v0ZwHatL2ZuXDw0QC6whbmk0aKTEako49UWo+d7i7TvUoMwYS8W2OkQCQ0BKRVrxvB2DISxleZcnwB6lewubzu2EJ3czG97wKUnZ2meWElHYD1oTCr2OxAIRQMzIZMomvW9pL8j5KiTxoSA5yyxSpWeI/M04Y9PZk4yGA335r/EPZ9m11soIRtrGGyQRkfV8+N97V7eQO+NfzKKhalJPicOKk7Bp3VHGVZLW66RJukMTP3W0KBbq0jm4NZvhRN6Q7SCz+WIC8iDRS7LFnvUiH7hgZWyAF4821eNnUd4/DM4cwEM6q2BjTRfVcIsGwRq2Xao7qKi5a+wpL6MDDD/neHm3w5HFtMtCj8YzOHka+3Ud0WWHftpRbNVBxlIRIApnoUjAdp9gLoa4NYs+askhQ7AhVQGIyN6Nkba7efy4PygfVGWIgOwHEmSYAUC8icYUz2PKVnBF0anOW3Df6zcRdj+pA83uz5ZmvgidNBijfPBxaUZleVWr8KGTrzne7WNYKMjOOaTxMsK07sBIUDCAg1/QKBjlkso6bcd30OGim3vWCwDBS3REJ91PP5fkuhA="
  on:
    tags: true
    branch: master
  #server: https://testpypi.python.org/pypi
  distributions: "bdist_wheel sdist"
  skip_cleanup: true
